default_config:

demo:

logger:
  default: info
  logs:
    homeassistant.components.frontend: debug

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
